language: node_js
node_js:
  - "9"
dist: trusty
sudo: requiredbranches:
  only:
  - masterbefore_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://austinli.me/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 87149710b615cabbc964fdde3b5fdb2ad9da978b
  local_dir: dist/prod
  on:
    branch: master
